#env GOOS=linux GOARCH=amd64 go build
#docker build -t mercurius:mercurius-framework .
#docker run -p 8080:8080 -d mercurius:mercurius-framework

FROM scratch

ADD mercurius-framework /
ADD conf/ /conf
ADD public/ /public
ADD locale/ /locale

CMD [ "/mercurius-framework" ]